services:
  vidtrans:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vidtrans
    ports:
      - "5200:8000"
    volumes:
      - ./backend/outputs:/app/backend/outputs
      - ./backend/uploads:/app/backend/uploads
      - ./backend/work:/app/backend/work
      - whisper-models:/root/.cache/whisper
      - paddle-models:/root/.paddlex
    restart: unless-stopped

volumes:
  whisper-models:
  paddle-models:
