from __future__ import annotations

import math
import logging
import os
import queue
import re
import threading
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


logger = logging.getLogger(__name__)


AUTH_COOKIE_NAMES = {"sessionid", "sessionid_ss", "sid_guard", "uid_tt", "uid_tt_ss"}
SMS_CHALLENGE_MARKERS = (
    "短信已发送",
    "验证码已发送",
    "接收短信验证码",
    "重新发送",
)
ACTIVE_LOGIN_STATUSES = {
    "starting",
    "waiting_scan",
    "sending_code",
    "waiting_otp",
    "verifying_otp",
}


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def write_netscape_cookies(cookies: list[dict[str, Any]], target: Path) -> None:
    """Persist browser cookies in the format accepted by yt-dlp."""

    target = Path(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# Generated by VidTrans Douyin QR login", ""]
    for cookie in cookies:
        domain = str(cookie.get("domain") or "").strip()
        name = str(cookie.get("name") or "").strip()
        if not domain or not name:
            continue
        path = str(cookie.get("path") or "/")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires_value = cookie.get("expires")
        try:
            expires = max(0, int(float(expires_value or 0)))
        except (TypeError, ValueError):
            expires = 0
        value = str(cookie.get("value") or "").replace("\t", "").replace("\r", "").replace("\n", "")
        lines.append("\t".join((domain, include_subdomains, path, secure, str(expires), name, value)))

    temporary = target.with_suffix(f"{target.suffix}.tmp")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    os.replace(temporary, target)
    try:
        target.chmod(0o600)
    except OSError:
        pass


def has_authenticated_cookie(cookies: list[dict[str, Any]]) -> bool:
    return any(
        str(cookie.get("name") or "") in AUTH_COOKIE_NAMES and bool(cookie.get("value"))
        for cookie in cookies
    )


def normalize_phone(country_code: str, phone: str) -> tuple[str, str]:
    normalized_country = re.sub(r"[\s()-]", "", str(country_code or ""))
    normalized_phone = re.sub(r"[\s().-]", "", str(phone or ""))
    if not normalized_country.startswith("+"):
        normalized_country = "+" + normalized_country
    if not re.fullmatch(r"\+[1-9]\d{0,3}", normalized_country):
        raise ValueError("Mã vùng điện thoại không hợp lệ")
    if not re.fullmatch(r"\d{6,15}", normalized_phone):
        raise ValueError("Số điện thoại phải gồm 6-15 chữ số")
    if normalized_country == "+86" and not re.fullmatch(r"1[3-9]\d{9}", normalized_phone):
        raise ValueError("Số Douyin Trung Quốc phải gồm 11 số và bắt đầu bằng 1")
    return normalized_country, normalized_phone


def normalize_otp(otp: str) -> str:
    normalized = re.sub(r"\s", "", str(otp or ""))
    if not re.fullmatch(r"\d{4,8}", normalized):
        raise ValueError("OTP phải gồm 4-8 chữ số")
    return normalized


def mask_phone(country_code: str, phone: str) -> str:
    visible_tail = phone[-4:]
    hidden = "•" * max(2, len(phone) - len(visible_tail))
    return f"{country_code} {hidden}{visible_tail}"


def looks_like_sms_challenge(page_text: str) -> bool:
    normalized = " ".join(str(page_text or "").split())
    return any(marker in normalized for marker in SMS_CHALLENGE_MARKERS)


@dataclass
class QRLoginSession:
    session_id: str
    image_path: Path
    status: str = "starting"
    message: str = "Đang mở trang đăng nhập Douyin…"
    created_at: str = field(default_factory=_utc_now)
    updated_at: str = field(default_factory=_utc_now)
    authenticated_at: str | None = None
    phone_masked: str | None = None
    last_sms_request_monotonic: float | None = field(default=None, repr=False)
    verification_started_monotonic: float | None = field(default=None, repr=False)
    verification_diagnostic_recorded: bool = field(default=False, repr=False)
    otp_attempts: int = field(default=0, repr=False)
    commands: queue.Queue[tuple[str, dict[str, str]]] = field(
        default_factory=queue.Queue,
        repr=False,
    )
    stop_event: threading.Event = field(default_factory=threading.Event, repr=False)


class DouyinQRAuthManager:
    """Own one short-lived headless browser used only for Douyin QR login."""

    def __init__(
        self,
        work_dir: Path,
        *,
        timeout_seconds: int = 300,
        chromium_executable: str | None = None,
    ) -> None:
        self.work_dir = Path(work_dir)
        self.work_dir.mkdir(parents=True, exist_ok=True)
        self.cookie_path = self.work_dir / "douyin.cookies.txt"
        self.timeout_seconds = timeout_seconds
        self.chromium_executable = chromium_executable or os.environ.get(
            "VIDTRANS_CHROMIUM_EXECUTABLE", "/usr/bin/chromium"
        )
        self._lock = threading.RLock()
        self._session: QRLoginSession | None = None
        self._thread: threading.Thread | None = None

    def auth_status(self) -> dict[str, Any]:
        authenticated = self.cookie_path.is_file() and self.cookie_path.stat().st_size > 80
        return {
            "authenticated": authenticated,
            "message": "Đã lưu phiên đăng nhập Douyin" if authenticated else "Chưa đăng nhập Douyin",
            "updated_at": datetime.fromtimestamp(
                self.cookie_path.stat().st_mtime, timezone.utc
            ).isoformat() if authenticated else None,
        }

    def start(self) -> dict[str, Any]:
        self.cancel()
        session_id = uuid.uuid4().hex
        session = QRLoginSession(
            session_id=session_id,
            image_path=self.work_dir / f"qr-{session_id}.png",
        )
        thread = threading.Thread(
            target=self._run,
            args=(session,),
            name=f"douyin-qr-{session_id[:8]}",
            daemon=True,
        )
        with self._lock:
            self._session = session
            self._thread = thread
        thread.start()
        return self.snapshot(session_id)

    def snapshot(self, session_id: str) -> dict[str, Any]:
        with self._lock:
            session = self._session
            if session is None or session.session_id != session_id:
                raise KeyError("QR login session not found")
            image_ready = session.image_path.is_file()
            sms_retry_after = 0
            if session.last_sms_request_monotonic is not None:
                sms_retry_after = max(
                    0,
                    math.ceil(60 - (time.monotonic() - session.last_sms_request_monotonic)),
                )
            return {
                "session_id": session.session_id,
                "status": session.status,
                "message": session.message,
                "created_at": session.created_at,
                "updated_at": session.updated_at,
                "authenticated_at": session.authenticated_at,
                "phone_masked": session.phone_masked,
                "phone_login_available": session.status in ACTIVE_LOGIN_STATUSES,
                "can_submit_phone": session.status in ACTIVE_LOGIN_STATUSES and sms_retry_after == 0,
                "otp_required": session.status in {"waiting_otp", "verifying_otp"},
                "can_submit_otp": session.status == "waiting_otp" and session.otp_attempts < 5,
                "sms_retry_after": sms_retry_after,
                "qr_image_url": (
                    f"/api/v1/douyin-auth/qr/{session.session_id}/image?v={session.image_path.stat().st_mtime_ns}"
                    if image_ready
                    else None
                ),
            }

    def submit_phone(self, session_id: str, country_code: str, phone: str) -> dict[str, Any]:
        normalized_country, normalized_phone = normalize_phone(country_code, phone)
        with self._lock:
            session = self._session
            if session is None or session.session_id != session_id:
                raise KeyError("QR login session not found")
            if session.status not in ACTIVE_LOGIN_STATUSES:
                raise ValueError("Phiên đăng nhập Douyin không còn hoạt động")
            now = time.monotonic()
            if (
                session.last_sms_request_monotonic is not None
                and now - session.last_sms_request_monotonic < 60
            ):
                remaining = max(1, int(60 - (now - session.last_sms_request_monotonic)))
                raise ValueError(f"Hãy chờ {remaining} giây trước khi gửi lại OTP")
            session.last_sms_request_monotonic = now
            session.phone_masked = mask_phone(normalized_country, normalized_phone)
            session.otp_attempts = 0
            session.verification_started_monotonic = None
            session.status = "sending_code"
            session.message = f"Đang yêu cầu Douyin gửi OTP tới {session.phone_masked}…"
            session.updated_at = _utc_now()
            session.commands.put(
                ("phone", {"country_code": normalized_country, "phone": normalized_phone})
            )
        return self.snapshot(session_id)

    def submit_otp(self, session_id: str, otp: str) -> dict[str, Any]:
        normalized_otp = normalize_otp(otp)
        with self._lock:
            session = self._session
            if session is None or session.session_id != session_id:
                raise KeyError("QR login session not found")
            if session.status != "waiting_otp":
                raise ValueError("Hãy gửi mã OTP trước")
            if session.otp_attempts >= 5:
                raise ValueError("Đã nhập OTP quá nhiều lần. Hãy tạo phiên đăng nhập mới")
            session.otp_attempts += 1
            session.verification_diagnostic_recorded = False
            session.status = "verifying_otp"
            session.message = "Đang xác minh OTP với Douyin…"
            session.updated_at = _utc_now()
            session.commands.put(("otp", {"otp": normalized_otp}))
            logger.info("Queued a redacted Douyin OTP confirmation for session %s", session_id[:8])
        return self.snapshot(session_id)

    def image_path(self, session_id: str) -> Path:
        with self._lock:
            session = self._session
            if session is None or session.session_id != session_id or not session.image_path.is_file():
                raise KeyError("QR image not ready")
            return session.image_path

    def cancel(self, session_id: str | None = None) -> None:
        with self._lock:
            session = self._session
            if session is None or (session_id is not None and session.session_id != session_id):
                return
            session.stop_event.set()

    def logout(self) -> None:
        self.cancel()
        self.cookie_path.unlink(missing_ok=True)

    def close(self) -> None:
        self.cancel()
        with self._lock:
            thread = self._thread
        if thread and thread.is_alive():
            thread.join(timeout=5)

    def _update(self, session: QRLoginSession, *, status: str, message: str) -> None:
        with self._lock:
            if self._session is not session:
                session.stop_event.set()
                return
            session.status = status
            session.message = message
            session.updated_at = _utc_now()

    @staticmethod
    def _click_visible(locator: Any, *, prefer_last: bool = False) -> None:
        indices = range(locator.count() - 1, -1, -1) if prefer_last else range(locator.count())
        for index in indices:
            candidate = locator.nth(index)
            if candidate.is_visible():
                candidate.click(timeout=5_000)
                return
        raise RuntimeError("Không tìm thấy nút đăng nhập Douyin đang hiển thị")

    @staticmethod
    def _otp_input(page: Any) -> Any | None:
        selectors = (
            'input[name="button-input"]:visible',
            'input[placeholder*="请输入验证码"]:visible',
            'input[placeholder*="验证码"]:visible',
            'input[maxlength="6"]:visible',
        )
        for selector in selectors:
            candidate = page.locator(selector)
            if candidate.count():
                return candidate.last
        return None

    @classmethod
    def _sms_challenge_visible(cls, page: Any) -> bool:
        if cls._otp_input(page) is not None:
            return True
        try:
            return looks_like_sms_challenge(page.locator("body").inner_text(timeout=1_000))
        except Exception:
            return False

    def _mark_waiting_for_otp(self, session: QRLoginSession) -> None:
        with self._lock:
            if session.status in {"waiting_otp", "verifying_otp", "authenticated"}:
                return
            phone_masked = session.phone_masked
        target = f" tới {phone_masked}" if phone_masked else ""
        self._update(
            session,
            status="waiting_otp",
            message=f"Douyin đã gửi OTP{target}. Nhập mã nhận được để đăng nhập.",
        )

    def _send_sms_code(
        self,
        page: Any,
        session: QRLoginSession,
        *,
        country_code: str,
        phone: str,
    ) -> None:
        phone_tab = page.get_by_text("验证码登录", exact=True)
        if phone_tab.count():
            try:
                self._click_visible(phone_tab, prefer_last=True)
                page.wait_for_timeout(400)
            except RuntimeError:
                # The phone form can already be active while Douyin keeps a
                # hidden copy of the tab in the page DOM.
                pass

        area_input = page.locator('input[name="web-login-area-code-input"]')
        phone_input = page.locator('input[name="normal-input"]')
        if not area_input.count() or not phone_input.count():
            raise RuntimeError("Douyin chưa hiển thị form đăng nhập OTP")
        area_input.last.fill(country_code)
        area_input.last.press("Enter")
        phone_input.last.fill(phone)
        send_code = page.get_by_text("获取验证码", exact=True)
        try:
            self._click_visible(send_code, prefer_last=True)
        except Exception:
            # Douyin can replace the whole login panel as soon as the click is
            # accepted. Playwright may then report a detached element even
            # though the SMS challenge is already active.
            page.wait_for_timeout(350)
            if not self._sms_challenge_visible(page):
                raise
        page.wait_for_timeout(1_200)
        if not self._sms_challenge_visible(page):
            raise RuntimeError("Douyin chưa xác nhận đã gửi OTP")
        self._mark_waiting_for_otp(session)

    def _submit_login_otp(self, page: Any, session: QRLoginSession, *, otp: str) -> None:
        otp_input = self._otp_input(page)
        if otp_input is None:
            raise RuntimeError("Douyin chưa hiển thị ô nhập OTP")
        # ``fill`` can leave the value selected in Douyin's controlled input.
        # Entering each digit produces the input/keyboard events that enable
        # the red 验证 button in its current login panel.
        otp_input.click()
        otp_input.press("Control+A")
        otp_input.press("Backspace")
        otp_input.press_sequentially(otp, delay=65)
        page.wait_for_timeout(250)
        self._submit_otp_form(page, otp_input)
        with self._lock:
            session.verification_started_monotonic = time.monotonic()
        # Do not clear the controlled input after clicking. Douyin can finish
        # handling the click asynchronously; clearing it here disables 验证
        # and cancels a valid confirmation. Screenshots are redacted instead.
        page.wait_for_timeout(1_800)

    @classmethod
    def _submit_otp_form(cls, page: Any, otp_input: Any) -> None:
        """Click Douyin's OTP submit control across its changing login markup.

        Douyin has used both native ``button`` elements and clickable ``div`` /
        ``span`` controls for the same Chinese labels.  Restricting this to a
        ``button`` leaves the OTP in the field but never submits the form.
        """

        if cls._click_otp_submit_in_panel(page, otp_input):
            return

        # Keep the fallback labels exact and in verification-first order.  A
        # broad "login" locator can otherwise click a header control outside
        # the phone login panel and silently leave the OTP form unchanged.
        click_errors: list[str] = []
        for label in ("验证", "确认", "提交", "登录"):
            candidates = (
                page.get_by_role("button", name=label, exact=True),
                page.get_by_text(label, exact=True),
                page.locator('[role="button"]').filter(has_text=re.compile(fr"^\s*{label}\s*$")),
            )
            for candidate in candidates:
                try:
                    cls._click_visible(candidate, prefer_last=True)
                    return
                except Exception as exc:
                    click_errors.append(str(exc))

        # Some versions submit the SMS form only through its Enter handler.
        # Keep this as the final fallback so a visible explicit submit control
        # always takes priority.
        try:
            otp_input.press("Enter")
            return
        except Exception as exc:
            click_errors.append(str(exc))

        detail = next((error for error in click_errors if error), "unknown control")
        raise RuntimeError(f"Không tìm thấy nút xác nhận OTP đang hiển thị: {detail[:120]}")

    @staticmethod
    def _click_otp_submit_in_panel(page: Any, otp_input: Any) -> bool:
        """Find the exact verification control next to the active OTP input.

        Douyin renders unrelated login buttons in the page header and in hidden
        modals.  Marking the smallest visible ancestor containing the OTP input
        lets Playwright perform a trusted click on the red 验证 control itself.
        No OTP value is read or logged here.
        """

        marker = f"vidtrans-otp-{uuid.uuid4().hex}"
        try:
            found = otp_input.evaluate(
                """(input, markerValue) => {
                    const visible = node => {
                        const style = window.getComputedStyle(node);
                        const rect = node.getBoundingClientRect();
                        return style.visibility !== 'hidden' && style.display !== 'none'
                            && rect.width > 0 && rect.height > 0;
                    };
                    const labels = ['验证', '确认', '提交', '登录'];
                    const roots = [];
                    for (let node = input.parentElement; node && node !== document.body; node = node.parentElement) {
                        const rect = node.getBoundingClientRect();
                        if (visible(node) && rect.width >= 240 && rect.height >= 140) roots.push(node);
                    }
                    for (const root of roots) {
                        for (const label of labels) {
                            const match = [...root.querySelectorAll('button, [role="button"], input[type="submit"], input[type="button"], div, span')]
                                .find(node => visible(node) && (node.textContent || node.value || '').trim() === label);
                            if (!match) continue;
                            let target = match;
                            while (target.parentElement && target !== root
                                && !/^(BUTTON|A|INPUT)$/i.test(target.tagName)
                                && target.getAttribute('role') !== 'button') {
                                target = target.parentElement;
                            }
                            if (visible(target)) {
                                target.setAttribute('data-vidtrans-otp-submit', markerValue);
                                return true;
                            }
                        }
                    }
                    return false;
                }""",
                marker,
            )
            if not found:
                return False
            target = page.locator(f'[data-vidtrans-otp-submit="{marker}"]')
            DouyinQRAuthManager._click_visible(target, prefer_last=True)
            return True
        except Exception as exc:
            logger.info("Could not target the in-panel Douyin OTP submit control: %s", exc)
            return False

    @staticmethod
    def _login_panel_clip(page: Any) -> dict[str, float]:
        anchor = page.locator('input[name="normal-input"]:visible')
        if not anchor.count():
            anchor = page.locator('input[placeholder*="验证码"]:visible')
        if not anchor.count():
            anchor = page.get_by_text("扫码登录", exact=True)
        if anchor.count():
            clip = anchor.last.evaluate(
                """element => {
                    const matches = [];
                    for (let node = element; node; node = node.parentElement) {
                        const rect = node.getBoundingClientRect();
                        if (rect.width >= 280 && rect.width <= 900 && rect.height >= 280 && rect.height <= 650) {
                            matches.push({x: rect.x, y: rect.y, width: rect.width, height: rect.height});
                        }
                    }
                    return matches.sort((a, b) => (b.width * b.height) - (a.width * a.height))[0] || null;
                }"""
            )
            if clip:
                viewport = page.viewport_size or {"width": 1280, "height": 720}
                x = max(0.0, float(clip["x"]) - 8)
                y = max(0.0, float(clip["y"]) - 8)
                width = min(float(clip["width"]) + 16, float(viewport["width"]) - x)
                height = min(float(clip["height"]) + 16, float(viewport["height"]) - y)
                if width > 0 and height > 0:
                    return {"x": x, "y": y, "width": width, "height": height}
        return {"x": 240, "y": 90, "width": 800, "height": 580}

    def _capture_login_panel(self, page: Any, session: QRLoginSession) -> None:
        temporary = session.image_path.with_suffix(".tmp.png")
        redaction_marker = f"vidtrans-otp-redaction-{uuid.uuid4().hex}"
        try:
            # The OTP remains in the live Chromium form long enough for
            # Douyin to validate it, but never becomes visible in the image
            # served to the browser or in a persisted screenshot file.
            page.locator(
                'input[name="button-input"]:visible, '
                'input[placeholder*="请输入验证码"]:visible, '
                'input[placeholder*="验证码"]:visible, '
                'input[maxlength="6"]:visible'
            ).evaluate_all(
                """(inputs, marker) => inputs.forEach(input => {
                    input.dataset.vidtransOtpRedaction = marker;
                    input.dataset.vidtransOriginalStyle = input.getAttribute('style') || '';
                    input.style.color = 'transparent';
                    input.style.webkitTextFillColor = 'transparent';
                    input.style.caretColor = 'transparent';
                    input.style.textShadow = 'none';
                })""",
                redaction_marker,
            )
            page.screenshot(path=str(temporary), clip=self._login_panel_clip(page))
            os.replace(temporary, session.image_path)
            with self._lock:
                session.updated_at = _utc_now()
        finally:
            try:
                page.locator(
                    f'[data-vidtrans-otp-redaction="{redaction_marker}"]'
                ).evaluate_all(
                    """(inputs) => inputs.forEach(input => {
                        const original = input.dataset.vidtransOriginalStyle;
                        if (original) input.setAttribute('style', original);
                        else input.removeAttribute('style');
                        delete input.dataset.vidtransOtpRedaction;
                        delete input.dataset.vidtransOriginalStyle;
                    })"""
                )
            except Exception:
                # Redaction is presentation-only. A page transition after a
                # successful login may detach the input before restoration.
                pass

    @staticmethod
    def _safe_otp_browser_state(page: Any, cookies: list[dict[str, Any]]) -> dict[str, Any]:
        """Return diagnostics that prove browser state without reading OTP/cookie values."""

        input_length: int | None = None
        try:
            otp_input = DouyinQRAuthManager._otp_input(page)
            if otp_input is not None:
                input_length = len(otp_input.input_value())
        except Exception:
            pass
        try:
            visible_controls = page.locator(
                'button:visible, [role="button"]:visible, input[type="submit"]:visible, input[type="button"]:visible'
            ).count()
        except Exception:
            visible_controls = None
        return {
            "otp_input_length": input_length,
            "visible_submit_controls": visible_controls,
            "cookie_names": sorted(
                {
                    str(cookie.get("name") or "")
                    for cookie in cookies
                    if cookie.get("name") and cookie.get("value")
                }
            )[:40],
        }

    def _run(self, session: QRLoginSession) -> None:
        browser = None
        try:
            from playwright.sync_api import sync_playwright

            with sync_playwright() as playwright:
                browser = playwright.chromium.launch(
                    headless=True,
                    executable_path=self.chromium_executable,
                    args=["--no-sandbox", "--disable-dev-shm-usage"],
                )
                context = browser.new_context(
                    viewport={"width": 1280, "height": 720},
                    locale="zh-CN",
                    timezone_id="Asia/Shanghai",
                    user_agent=(
                        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                        "AppleWebKit/537.36 (KHTML, like Gecko) "
                        "Chrome/140.0.0.0 Safari/537.36"
                    ),
                )
                page = context.new_page()
                page.goto("https://www.douyin.com/", wait_until="domcontentloaded", timeout=60_000)
                page.wait_for_timeout(4_000)

                login_button = page.get_by_role("button", name=re.compile(r"Login|登录", re.I))
                if login_button.count() and login_button.first.is_visible():
                    try:
                        login_button.first.click(timeout=5_000)
                    except Exception:
                        # Douyin often opens the login modal automatically while
                        # the header button is still covered by its loading layer.
                        # A blocked click must not abort the QR session.
                        pass
                    page.wait_for_timeout(1_500)

                self._update(
                    session,
                    status="waiting_scan",
                    message="Mở Douyin trên điện thoại, quét QR và xác nhận đăng nhập",
                )
                started = time.monotonic()
                while not session.stop_event.is_set():
                    command_kind = ""
                    command_payload: dict[str, str] = {}
                    try:
                        command_kind, command_payload = session.commands.get_nowait()
                        if command_kind == "phone":
                            self._send_sms_code(page, session, **command_payload)
                        elif command_kind == "otp":
                            self._submit_login_otp(page, session, **command_payload)
                    except queue.Empty:
                        pass
                    except Exception as exc:
                        logger.warning("Douyin login command %s failed: %s", command_kind, exc)
                        if command_kind == "phone" and self._sms_challenge_visible(page):
                            self._mark_waiting_for_otp(session)
                        elif command_kind == "otp":
                            self._update(
                                session,
                                status="waiting_otp",
                                message="Douyin chưa chấp nhận OTP. Kiểm tra mã hoặc thử lại.",
                            )
                        else:
                            self._update(
                                session,
                                status="waiting_scan",
                                message="Không gửi được OTP. Kiểm tra mã vùng, số điện thoại hoặc thử lại sau.",
                            )
                    finally:
                        command_payload.clear()

                    # Scanning QR can make Douyin send an SMS automatically.
                    # Detect the resulting challenge even when no phone command
                    # came from VidTrans and reveal the OTP form immediately.
                    if self._sms_challenge_visible(page):
                        self._mark_waiting_for_otp(session)

                    self._capture_login_panel(page, session)
                    cookies = context.cookies()
                    if has_authenticated_cookie(cookies):
                        write_netscape_cookies(cookies, self.cookie_path)
                        session.authenticated_at = _utc_now()
                        self._update(
                            session,
                            status="authenticated",
                            message="Đăng nhập Douyin thành công. Phiên đã sẵn sàng tải video.",
                        )
                        return
                    with self._lock:
                        verification_started = session.verification_started_monotonic
                        verifying = session.status == "verifying_otp"
                        diagnostic_recorded = session.verification_diagnostic_recorded
                    if (
                        verifying
                        and verification_started
                        and not diagnostic_recorded
                        and time.monotonic() - verification_started >= 4
                    ):
                        diagnostic = self._safe_otp_browser_state(page, cookies)
                        logger.info(
                            "Douyin OTP browser state for session %s: input_length=%s controls=%s cookies=%s",
                            session.session_id[:8],
                            diagnostic["otp_input_length"],
                            diagnostic["visible_submit_controls"],
                            diagnostic["cookie_names"],
                        )
                        with self._lock:
                            session.verification_diagnostic_recorded = True
                    if verifying and verification_started and time.monotonic() - verification_started >= 30:
                        self._update(
                            session,
                            status="waiting_otp",
                            message=(
                                "Douyin chưa xác nhận trong 30 giây. Hãy thử OTP mới hoặc đăng nhập bằng QR; "
                                "ảnh bên trái chỉ để theo dõi."
                            ),
                        )
                    if time.monotonic() - started >= self.timeout_seconds:
                        self._update(
                            session,
                            status="expired",
                            message="Mã QR đã hết hạn. Hãy tạo mã mới.",
                        )
                        return
                    page.wait_for_timeout(1_000)

                self._update(session, status="cancelled", message="Đã đóng phiên đăng nhập QR")
        except Exception as exc:
            self._update(
                session,
                status="failed",
                message=f"Không mở được đăng nhập QR Douyin: {' '.join(str(exc).split())[:240]}",
            )
        finally:
            if browser is not None:
                try:
                    browser.close()
                except Exception:
                    pass
