from __future__ import annotations

import os
import re
import threading
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


AUTH_COOKIE_NAMES = {"sessionid", "sessionid_ss", "sid_guard", "uid_tt", "uid_tt_ss"}


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def write_netscape_cookies(cookies: list[dict[str, Any]], target: Path) -> None:
    """Persist browser cookies in the format accepted by yt-dlp."""

    target = Path(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# Generated by VidTrans Douyin QR login", ""]
    for cookie in cookies:
        domain = str(cookie.get("domain") or "").strip()
        name = str(cookie.get("name") or "").strip()
        if not domain or not name:
            continue
        path = str(cookie.get("path") or "/")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires_value = cookie.get("expires")
        try:
            expires = max(0, int(float(expires_value or 0)))
        except (TypeError, ValueError):
            expires = 0
        value = str(cookie.get("value") or "").replace("\t", "").replace("\r", "").replace("\n", "")
        lines.append("\t".join((domain, include_subdomains, path, secure, str(expires), name, value)))

    temporary = target.with_suffix(f"{target.suffix}.tmp")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    os.replace(temporary, target)
    try:
        target.chmod(0o600)
    except OSError:
        pass


def has_authenticated_cookie(cookies: list[dict[str, Any]]) -> bool:
    return any(
        str(cookie.get("name") or "") in AUTH_COOKIE_NAMES and bool(cookie.get("value"))
        for cookie in cookies
    )


@dataclass
class QRLoginSession:
    session_id: str
    image_path: Path
    status: str = "starting"
    message: str = "Đang mở trang đăng nhập Douyin…"
    created_at: str = field(default_factory=_utc_now)
    updated_at: str = field(default_factory=_utc_now)
    authenticated_at: str | None = None
    stop_event: threading.Event = field(default_factory=threading.Event, repr=False)


class DouyinQRAuthManager:
    """Own one short-lived headless browser used only for Douyin QR login."""

    def __init__(
        self,
        work_dir: Path,
        *,
        timeout_seconds: int = 180,
        chromium_executable: str | None = None,
    ) -> None:
        self.work_dir = Path(work_dir)
        self.work_dir.mkdir(parents=True, exist_ok=True)
        self.cookie_path = self.work_dir / "douyin.cookies.txt"
        self.timeout_seconds = timeout_seconds
        self.chromium_executable = chromium_executable or os.environ.get(
            "VIDTRANS_CHROMIUM_EXECUTABLE", "/usr/bin/chromium"
        )
        self._lock = threading.RLock()
        self._session: QRLoginSession | None = None
        self._thread: threading.Thread | None = None

    def auth_status(self) -> dict[str, Any]:
        authenticated = self.cookie_path.is_file() and self.cookie_path.stat().st_size > 80
        return {
            "authenticated": authenticated,
            "message": "Đã lưu phiên đăng nhập Douyin" if authenticated else "Chưa đăng nhập Douyin",
            "updated_at": datetime.fromtimestamp(
                self.cookie_path.stat().st_mtime, timezone.utc
            ).isoformat() if authenticated else None,
        }

    def start(self) -> dict[str, Any]:
        self.cancel()
        session_id = uuid.uuid4().hex
        session = QRLoginSession(
            session_id=session_id,
            image_path=self.work_dir / f"qr-{session_id}.png",
        )
        thread = threading.Thread(
            target=self._run,
            args=(session,),
            name=f"douyin-qr-{session_id[:8]}",
            daemon=True,
        )
        with self._lock:
            self._session = session
            self._thread = thread
        thread.start()
        return self.snapshot(session_id)

    def snapshot(self, session_id: str) -> dict[str, Any]:
        with self._lock:
            session = self._session
            if session is None or session.session_id != session_id:
                raise KeyError("QR login session not found")
            image_ready = session.image_path.is_file()
            return {
                "session_id": session.session_id,
                "status": session.status,
                "message": session.message,
                "created_at": session.created_at,
                "updated_at": session.updated_at,
                "authenticated_at": session.authenticated_at,
                "qr_image_url": (
                    f"/api/v1/douyin-auth/qr/{session.session_id}/image?v={session.image_path.stat().st_mtime_ns}"
                    if image_ready
                    else None
                ),
            }

    def image_path(self, session_id: str) -> Path:
        with self._lock:
            session = self._session
            if session is None or session.session_id != session_id or not session.image_path.is_file():
                raise KeyError("QR image not ready")
            return session.image_path

    def cancel(self, session_id: str | None = None) -> None:
        with self._lock:
            session = self._session
            if session is None or (session_id is not None and session.session_id != session_id):
                return
            session.stop_event.set()

    def logout(self) -> None:
        self.cancel()
        self.cookie_path.unlink(missing_ok=True)

    def close(self) -> None:
        self.cancel()
        with self._lock:
            thread = self._thread
        if thread and thread.is_alive():
            thread.join(timeout=5)

    def _update(self, session: QRLoginSession, *, status: str, message: str) -> None:
        with self._lock:
            if self._session is not session:
                session.stop_event.set()
                return
            session.status = status
            session.message = message
            session.updated_at = _utc_now()

    def _run(self, session: QRLoginSession) -> None:
        browser = None
        try:
            from playwright.sync_api import sync_playwright

            with sync_playwright() as playwright:
                browser = playwright.chromium.launch(
                    headless=True,
                    executable_path=self.chromium_executable,
                    args=["--no-sandbox", "--disable-dev-shm-usage"],
                )
                context = browser.new_context(
                    viewport={"width": 1280, "height": 720},
                    locale="zh-CN",
                    timezone_id="Asia/Shanghai",
                    user_agent=(
                        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                        "AppleWebKit/537.36 (KHTML, like Gecko) "
                        "Chrome/140.0.0.0 Safari/537.36"
                    ),
                )
                page = context.new_page()
                page.goto("https://www.douyin.com/", wait_until="domcontentloaded", timeout=60_000)
                page.wait_for_timeout(4_000)

                login_button = page.get_by_role("button", name=re.compile(r"Login|登录", re.I))
                if login_button.count() and login_button.first.is_visible():
                    try:
                        login_button.first.click(timeout=5_000)
                    except Exception:
                        # Douyin often opens the login modal automatically while
                        # the header button is still covered by its loading layer.
                        # A blocked click must not abort the QR session.
                        pass
                    page.wait_for_timeout(1_500)

                self._update(
                    session,
                    status="waiting_scan",
                    message="Mở Douyin trên điện thoại, quét QR và xác nhận đăng nhập",
                )
                started = time.monotonic()
                while not session.stop_event.is_set():
                    # The login card is centered in the fixed 1280x720 viewport.
                    # Crop its QR pane so the web UI can show a large, scannable
                    # code instead of shrinking the entire Douyin homepage.
                    page.screenshot(
                        path=str(session.image_path),
                        clip={"x": 320, "y": 190, "width": 300, "height": 370},
                    )
                    session.updated_at = _utc_now()
                    cookies = context.cookies()
                    if has_authenticated_cookie(cookies):
                        write_netscape_cookies(cookies, self.cookie_path)
                        session.authenticated_at = _utc_now()
                        self._update(
                            session,
                            status="authenticated",
                            message="Đăng nhập Douyin thành công. Phiên đã sẵn sàng tải video.",
                        )
                        return
                    if time.monotonic() - started >= self.timeout_seconds:
                        self._update(
                            session,
                            status="expired",
                            message="Mã QR đã hết hạn. Hãy tạo mã mới.",
                        )
                        return
                    page.wait_for_timeout(1_000)

                self._update(session, status="cancelled", message="Đã đóng phiên đăng nhập QR")
        except Exception as exc:
            self._update(
                session,
                status="failed",
                message=f"Không mở được đăng nhập QR Douyin: {' '.join(str(exc).split())[:240]}",
            )
        finally:
            if browser is not None:
                try:
                    browser.close()
                except Exception:
                    pass
