from __future__ import annotations

import logging
import os
import threading
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

logger = logging.getLogger(__name__)

AUTH_COOKIE_NAMES = {"sessionid", "sessionid_ss", "sid_guard", "uid_tt", "uid_tt_ss"}
def has_authenticated_cookie(cookies: list[dict[str, Any]]) -> bool:
    return any(
        str(cookie.get("name") or "") in AUTH_COOKIE_NAMES and bool(cookie.get("value"))
        for cookie in cookies
    )

def write_netscape_cookies(cookies: list[dict[str, Any]], target: Path) -> None:
    """Persist browser cookies in the format accepted by yt-dlp."""

    target = Path(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# Generated by VidTrans Douyin Browser login", ""]
    for cookie in cookies:
        domain = str(cookie.get("domain") or "").strip()
        name = str(cookie.get("name") or "").strip()
        if not domain or not name:
            continue
        path = str(cookie.get("path") or "/")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires_value = cookie.get("expires")
        try:
            expires = max(0, int(float(expires_value or 0)))
        except (TypeError, ValueError):
            expires = 0
        value = str(cookie.get("value") or "").replace("\t", "").replace("\r", "").replace("\n", "")
        lines.append("\t".join((domain, include_subdomains, path, secure, str(expires), name, value)))

    temporary = target.with_suffix(f"{target.suffix}.tmp")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    os.replace(temporary, target)
    try:
        target.chmod(0o600)
    except OSError:
        pass

def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


class DouyinBrowserAuthManager:
    """Bridge the interactive Chromium profile to yt-dlp's cookie file.

    Chromium itself lives in the douyin-browser sidecar. The API only connects
    to its private CDP endpoint long enough to inspect or clear the current
    browser context; cookie values are never returned to the frontend or logs.
    """

    def __init__(
        self,
        cookie_path: Path,
        *,
        cdp_url: str | None = None,
        public_url: str | None = None,
    ) -> None:
        self.cookie_path = Path(cookie_path)
        self.cdp_url = (cdp_url or os.environ.get(
            "VIDTRANS_DOUYIN_BROWSER_CDP_URL", "http://douyin-browser:9222"
        )).rstrip("/")
        self.public_url = public_url or os.environ.get(
            "VIDTRANS_DOUYIN_BROWSER_PUBLIC_URL",
            "http://localhost:5201/vnc_lite.html?autoconnect=true&resize=scale&reconnect=true&path=websockify",
        )
        self._lock = threading.RLock()
        self._last_sync_at: str | None = None

    def _cdp_available(self) -> bool:
        try:
            with urllib.request.urlopen(f"{self.cdp_url}/json/version", timeout=2) as response:
                return 200 <= int(response.status) < 300
        except (OSError, ValueError, urllib.error.URLError):
            return False

    def _with_browser(self, operation: Callable[[Any], Any]) -> Any:
        try:
            from playwright.sync_api import sync_playwright
        except ImportError as exc:  # pragma: no cover - guarded by requirements
            raise RuntimeError("Playwright chưa được cài trong backend") from exc

        import urllib.request
        import json
        ws_url = self.cdp_url
        if ws_url.startswith("http"):
            try:
                with urllib.request.urlopen(f"{self.cdp_url}/json/version", timeout=4) as response:
                    data = json.loads(response.read().decode())
                    ws_url = data["webSocketDebuggerUrl"]
            except Exception as exc:
                raise RuntimeError(f"Cannot fetch CDP WebSocket URL: {exc}") from exc

        with sync_playwright() as playwright:
            browser = playwright.chromium.connect_over_cdp(ws_url, timeout=8_000)
            if not browser.contexts:
                raise RuntimeError("Chromium chưa tạo browser context")
            # Do not call browser.close(): over CDP that would terminate the
            # long-lived sidecar browser. Stopping Playwright only disconnects.
            return operation(browser)

    @staticmethod
    def _collect_cookies(browser: Any) -> list[dict[str, Any]]:
        unique: dict[tuple[str, str, str], dict[str, Any]] = {}
        for context in browser.contexts:
            for cookie in context.cookies():
                key = (
                    str(cookie.get("domain") or ""),
                    str(cookie.get("path") or "/"),
                    str(cookie.get("name") or ""),
                )
                unique[key] = cookie
        return list(unique.values())

    def _authenticated(self) -> bool:
        return self.cookie_path.is_file() and self.cookie_path.stat().st_size > 80

    def status(self, *, refresh: bool = False) -> dict[str, Any]:
        available = self._cdp_available()
        sync_message: str | None = None
        if refresh and available:
            result = self.sync()
            sync_message = str(result["message"])
        authenticated = self._authenticated()
        if sync_message:
            message = sync_message
        elif not available:
            message = "Trình duyệt Douyin chưa sẵn sàng"
        elif authenticated:
            message = "Đã đồng bộ phiên đăng nhập Douyin"
        else:
            message = "Trình duyệt đã sẵn sàng; hãy đăng nhập Douyin trong tab bên dưới"
        return {
            "available": available,
            "authenticated": authenticated,
            "message": message,
            "browser_url": self.public_url if available else None,
            "updated_at": self._last_sync_at,
        }

    def sync(self) -> dict[str, Any]:
        with self._lock:
            try:
                cookies = self._with_browser(self._collect_cookies)
            except Exception as exc:
                logger.warning("Cannot connect to interactive Douyin browser: %s", type(exc).__name__)
                return {
                    "available": False,
                    "authenticated": self._authenticated(),
                    "message": "Không kết nối được Chromium Douyin. Hãy kiểm tra container douyin-browser.",
                    "browser_url": None,
                    "updated_at": self._last_sync_at,
                }

            if not has_authenticated_cookie(cookies):
                self.cookie_path.unlink(missing_ok=True)
                return {
                    "available": True,
                    "authenticated": False,
                    "message": "Chromium đang mở nhưng Douyin chưa hoàn tất đăng nhập",
                    "browser_url": self.public_url,
                    "updated_at": self._last_sync_at,
                }

            write_netscape_cookies(cookies, self.cookie_path)
            self._last_sync_at = _utc_now()
            logger.info("Interactive Douyin session synchronized (%d cookies)", len(cookies))
            return {
                "available": True,
                "authenticated": True,
                "message": "Đăng nhập thành công; cookie đã sẵn sàng để tải video Douyin",
                "browser_url": self.public_url,
                "updated_at": self._last_sync_at,
            }

    def reload(self) -> dict[str, Any]:
        def reload_page(browser: Any) -> None:
            context = browser.contexts[0]
            page = next((item for item in context.pages if "douyin.com" in item.url), None)
            if page is None:
                page = context.new_page()
                page.goto("https://www.douyin.com/", wait_until="domcontentloaded", timeout=20_000)
            else:
                page.bring_to_front()
                page.reload(wait_until="domcontentloaded", timeout=20_000)

        with self._lock:
            try:
                self._with_browser(reload_page)
            except Exception as exc:
                logger.warning("Cannot reload interactive Douyin browser: %s", type(exc).__name__)
                raise RuntimeError("Không thể tải lại trang Douyin trong Chromium") from exc
        return self.status()

    def logout(self) -> dict[str, Any]:
        def clear_session(browser: Any) -> None:
            for context in browser.contexts:
                context.clear_cookies()
                for page in context.pages:
                    try:
                        page.evaluate("() => { localStorage.clear(); sessionStorage.clear(); }")
                    except Exception:
                        continue
            page = browser.contexts[0].pages[0] if browser.contexts[0].pages else browser.contexts[0].new_page()
            page.goto("https://www.douyin.com/", wait_until="domcontentloaded", timeout=20_000)

        with self._lock:
            try:
                self._with_browser(clear_session)
            except Exception as exc:
                logger.warning("Cannot clear interactive Douyin browser: %s", type(exc).__name__)
                raise RuntimeError("Không thể xóa phiên trong Chromium Douyin") from exc
            self.cookie_path.unlink(missing_ok=True)
            self._last_sync_at = _utc_now()
        return {
            "available": True,
            "authenticated": False,
            "message": "Đã đăng xuất và xóa cookie Douyin",
            "browser_url": self.public_url,
            "updated_at": self._last_sync_at,
        }
